---
name: Lingua-Han-Utils
version: 0.10
author:
  - 'Fayland Lam <fayland@gmail.com>'
abstract: The utility tools of Chinese character(HanZi)
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Encode::Guess: 0
  Test::More: 0
provides:
  Lingua::Han::Utils:
    file: lib/Lingua/Han/Utils.pm
    version: 0.10
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
